### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by marknopfler** [DeathAngelDaemon/display-lotro-server#4]
Hi!
I installed this plugin 1 month ago and all was working properly. But right now lotro is under maintenance. I get this error and wordpress causes error 500:

`Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't find <definitions> in 'http://gls.lotro.com/GLS.DataCenterServer/Service.asmx?WSDL' in /var/www/wordpress/wp-content/plugins/display-lotro-server-master/display-lotro-server.php:187 Stack trace: #0 /var/www/wordpress/wp-content/plugins/display-lotro-server-master/display-lotro-server.php(187): SoapClient->SoapClient('http://gls.lotr...') #1 /var/www/wordpress/wp-content/plugins/display-lotro-server-master/display-lotro-server.php(62): DisplayLotroServer->get_datacenter_result() #2 /var/www/wordpress/wp-content/plugins/display-lotro-server-master/display-lotro-server.php(348): DisplayLotroServer->__construct() #3 /var/www/wordpress/wp-settings.php(304): include_once('/var/www/wordpr...') #4 /var/www/wordpress/wp-config.php(70): require_once('/var/www/wordpr...') #5 /var/www/wordpress/wp-load.php(37): require_once('/var/www/wordpr...') #6 /var/www/wordpress/wp-blog-header.php(13): require_once('/var/www/wordpr...') #7 /var/www/wordpress/ind in /var/www/wordpress/wp-content/plugins/display-lotro-server-master/display-lotro-server.php on line 187`

Any help?????

**Comment by annaf-dev** [comment]
Hi,
sorry for the missing answer yet. I did not get any notification about your issue… Strange.
I will investigate this but it might need a new maintenance to test it.
Best regards
Anna

**Comment by annaf-dev** [comment]
Please download the newest Version (1.4) to fix this Output.
The users will see a normal message about missing server information while a new log file is created when this error occurs (the log file can then be found in the plugin folder, in a new folder called "logs").

**Comment by marknopfler** [comment]
Great, thank you! ;)
Installed here: legiones.es
